"""event based game tables built

Revision ID: 9c60c3a0fa2b
Revises: 
Create Date: 2021-10-21 11:23:04.816451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c60c3a0fa2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_players', sa.Integer(), nullable=True),
    sa.Column('spies', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=True),
    sa.Column('agent_src', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_token'), 'students', ['token'], unique=True)
    op.create_table('plays',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('agent_number', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'student_id')
    )
    op.create_table('rounds',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('missions',
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('mission_num', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.Column('team_string', sa.String(length=5), nullable=True),
    sa.Column('vote_string', sa.String(length=10), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('fails', sa.String(length=4), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('mission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_table('rounds')
    op.drop_table('plays')
    op.drop_index(op.f('ix_students_token'), table_name='students')
    op.drop_table('students')
    op.drop_table('games')
    # ### end Alembic commands ###
